### ISSUE TITLE
Stuff to ask Last Class

### ISSUE THREAD

**Issue by yashasaxena** [jhoballah/Melanoma_JSY#24]
1) get_prediction function takes in an image. We will be receiving image as b64, then decoding it. I re-encoded it as variable "img"

In order to make it a real image I had to do this: 
with open(filename, 'wb') as f:
...     f.write(img)

This saved image into my current directory. My question is will we need to do something like this in order to use get_prediction(image). If so, can we store the image from our Flask app? Where would it go? 

2) Sonali created a container a couple days ago, and is able to run a sample flask app that returns a string to @app.route('/') - this container has been stopped and restarted and works in successfully returning the string to the URL

Today we tried to do the same with a new container but are having issues and are curious about a number of things including if __name__="__main__":, with endpoints, without specified endpoints, trying both the original mains.py file vs the new image_send_flask.py file, etc. we are not sure why, but at some point we had not secure connection so removed the s, then got URL not found, but now we are back to err_connection_refused. We think there are some "rules" we are not following in our attempts but haven't figured out what is wrong.

This is all in imgproc branch and using the vcm admin account 

3) Material UI component questions  
- how to pass image from upload component to material UI component

**Comment by ss842** [comment]
1. get_prediction function takes in an image. We will be receiving image as b64, then decoding it. I re-encoded it as variable "img"
In order to make it a real image I had to do this:
with open(filename, 'wb') as f:
... f.write(img)

This saved image into my current directory. My question is will we need to do something like this in order to use get_prediction(image). If so, can we store the image from our Flask app? Where would it go?

2. Material UI component questions
how to pass image from upload component to material UI component

3. can you have multiple CMD lines in Dockerfile, if so, what is the syntax to make it successful?

**Comment by ss842** [comment]
@yashasaxena @jhoballah can we close this issue? and open specific issues when they come up? i know we asked about question 1, and question 3 is irrelevant to me now. not sure about  question 2.

**Comment by jhoballah** [comment]
I'm ready to close it, @yashasaxena do you have anything left for this?
