### ISSUE TITLE
Raspberry Pi Desktop GUI

### ISSUE THREAD

**Issue by yashasaxena** [jhoballah/Melanoma_JSY#6]
Hi,

Sorry to bother over break! No urgency. I just started to toy around with the Pi and realized there are some gaps for me. 

Couple things:
1) Can you remind me of the username/pw? It's in my notebook that I left in Durham.

2) If I wanted to use my Mac to remote desktop the raspberry pi, would I use this approach through an ethernet cable --> [https://www.dexterindustries.com/BrickPi/brickpi-tutorials-documentation/getting-started/using-the-pi/connect-to-your-raspberry-pi-from-a-mac/](https://www.dexterindustries.com/BrickPi/brickpi-tutorials-documentation/getting-started/using-the-pi/connect-to-your-raspberry-pi-from-a-mac/)

I'm assuming this is how we can best write programs on the pi, or if there's a better approach what would that be? Initially, I assumed we could upload on the SD card directly, but I don't think that's the case after doing some web research...

3) If I want the program to run as soon as and so long as the raspberry pi is powered, write a systemd file for the pi? 
https://www.raspberrypi.org/documentation/linux/usage/systemd.md

Also, if we could do some brief coverage in class, that would also be great!

Thanks,
Yasha

**Comment by mlp6** [comment]
I'm hoping @ad12 will be able to share the username/password since I also don't have that information with me.  You can develop all of your client code off the pi and on your laptop if you would like, and then just clone the git repo to the Pi when you want to run it there.  Access the GUI via your network connect might (1) be slow, and (2) might make it trickier to use a package like PyCharm on the Pi.  W/r to the automatic system startup, 'yes', we will be using a script that is run at boot time to get things kicked off automatically for us.  This will either use `systemd` or an `rc.local` approach (to be covered in class).
